const DEFAULT_API_URL = "";
const ADMIN_PASS = "Meridional";

const fallback = {
  tiendas:["Castro","Ancud","Osorno","Valdivia","Puerto Varas","Puerto Montt","Paseo Costanera","Villarrica","Kiosco Plaza Los Ríos","Kiosco Mall Castro"],
  jornada:{numero:1,total:7,fecha:"Viernes 19 de junio",premio:"🍕 Pizza Familiar con delivery al almuerzo del día hábil siguiente",condicion:"Cumplir Accesorios, Seguros y WOMGO del día"},
  partidos:[
    {hora:"15:00",local:"Estados Unidos",visita:"Australia",resultado:"Pendiente",ganador:""},
    {hora:"18:00",local:"Escocia",visita:"Marruecos",resultado:"Pendiente",ganador:""},
    {hora:"21:00",local:"Brasil",visita:"Haití",resultado:"Pendiente",ganador:""},
    {hora:"00:00",local:"Turquía",visita:"Paraguay",resultado:"Pendiente",ganador:""}
  ],
  metas:[
    {tienda:"Castro",condicion:true,kpis:[{nombre:"Accesorios",avance:250000,meta:300000,tipo:"$"},{nombre:"Seguros",avance:2,meta:3,tipo:"Q"},{nombre:"WOMGO",avance:1,meta:1,tipo:"Q"}]},
    {tienda:"Ancud",condicion:false,kpis:[{nombre:"Accesorios",avance:120000,meta:250000,tipo:"$"},{nombre:"Seguros",avance:1,meta:2,tipo:"Q"},{nombre:"WOMGO",avance:0,meta:1,tipo:"Q"}]}
  ],
  resultadoJornada:{estado:"pendiente",ganador:"",aciertos:0,mensaje:"El ganador de la jornada será informado al cierre."},
  apuestas:[]
};

let tiendas=[...fallback.tiendas], jornada={...fallback.jornada}, partidos=[...fallback.partidos], metas=[...fallback.metas];
let resultadoJornada={...fallback.resultadoJornada}, apuestas=JSON.parse(localStorage.getItem("apuestas_wom")||"[]");
let ultimaApuesta=null, apiUrl=localStorage.getItem("api_wom")||DEFAULT_API_URL;

document.addEventListener("DOMContentLoaded",async()=>{iniciarSplash();await cargarDesdeServidor(false);renderAll();showSection("inicio");});
function renderAll(){cargarInicio();cargarFormularioApuesta();cargarPronosticos();cargarMetas();cargarResultados();cargarAdmin();}
function getApiUrl(){return(localStorage.getItem("api_wom")||DEFAULT_API_URL||"").trim();}
async function apiGet(action,params={}){const url=getApiUrl();if(!url)throw new Error("API no configurada");const qs=new URLSearchParams({action,...params,t:Date.now()});const res=await fetch(`${url}?${qs}`);if(!res.ok)throw new Error("Error API");return await res.json();}
async function apiPost(action,payload){const url=getApiUrl();if(!url)throw new Error("API no configurada");const res=await fetch(url,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});if(!res.ok)throw new Error("No se pudo guardar");return await res.json();}
async function cargarDesdeServidor(showAlert=true){try{const data=await apiGet("bootstrap");tiendas=data.tiendas?.length?data.tiendas:tiendas;jornada=data.jornada||jornada;partidos=data.partidos?.length?data.partidos:partidos;metas=data.metas?.length?data.metas:metas;resultadoJornada=data.resultadoJornada||resultadoJornada;apuestas=data.apuestas||[];localStorage.setItem("apuestas_wom",JSON.stringify(apuestas));if(showAlert)alert("Datos actualizados desde Google Sheets.");renderAll();}catch(e){apuestas=JSON.parse(localStorage.getItem("apuestas_wom")||"[]");if(showAlert)alert("No se pudo conectar. Usando datos locales.");}}
async function probarConexion(){try{await apiGet("ping");alert("Conexión OK.");}catch(e){alert("No conecta. Revisa URL del Apps Script y permisos.");}}

function iniciarSplash(){const textos=["Cargando jornada...","Preparando partidos...","¡Que comience la competencia!"];let index=0;const loadingText=document.getElementById("loadingText");const intervalo=setInterval(()=>{index++;if(loadingText&&textos[index])loadingText.textContent=textos[index];},1300);setTimeout(()=>{clearInterval(intervalo);document.getElementById("splashScreen").style.display="none";document.getElementById("app").classList.remove("hidden");},4000);}
function showSection(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));const section=document.getElementById(id);if(section)section.classList.add("active");if(id==="pronosticos")cargarPronosticos();if(id==="resultados")cargarResultados();if(id==="condicionMeta")cargarMetas();window.scrollTo({top:0,behavior:"smooth"});}
function cargarInicio(){setText("jornadaActual",`${jornada.numero} de ${jornada.total}`);setText("fechaJornada",jornada.fecha);setText("premioDia",jornada.premio);const cont=document.getElementById("partidosHoy");if(!cont)return;cont.innerHTML=partidos.map(p=>`<div class="match-card"><div class="match-time">${escapeHTML(p.hora)}</div><div class="match-teams">${escapeHTML(p.local)} <span>VS</span> ${escapeHTML(p.visita)}</div></div>`).join("");}
function cargarFormularioApuesta(){const sel=document.getElementById("tienda");if(sel){sel.innerHTML=`<option value="">Seleccionar tienda</option>`;tiendas.forEach(t=>sel.innerHTML+=`<option value="${escapeAttr(t)}">${escapeHTML(t)}</option>`);sel.onchange=revisarTiendaSeleccionada;}const form=document.getElementById("formPartidos");if(form){form.innerHTML=partidos.map((p,i)=>`<div class="bet-card"><h3>⚽ ${escapeHTML(p.hora)}</h3><p>${escapeHTML(p.local)} VS ${escapeHTML(p.visita)}</p><select id="pronostico_${i}"><option value="">Seleccionar ganador</option><option value="${escapeAttr(p.local)}">${escapeHTML(p.local)}</option><option value="Empate">Empate</option><option value="${escapeAttr(p.visita)}">${escapeHTML(p.visita)}</option></select></div>`).join("");}resetFormularioApuesta();}
function revisarTiendaSeleccionada(){const tienda=document.getElementById("tienda")?.value;resetFormularioApuesta();if(!tienda)return;const registrada=apuestas.find(a=>a.tienda===tienda&&Number(a.jornada)===Number(jornada.numero));if(registrada){ultimaApuesta=registrada;registrada.elecciones.forEach((e,i)=>{const select=document.getElementById(`pronostico_${i}`);if(select)select.value=e.eleccion;});mostrarApuestaGuardada(registrada);}}
async function guardarApuesta(){const tienda=document.getElementById("tienda")?.value;if(!tienda)return alert("Selecciona una tienda.");const yaExiste=apuestas.find(a=>a.tienda===tienda&&Number(a.jornada)===Number(jornada.numero));if(yaExiste){ultimaApuesta=yaExiste;mostrarApuestaGuardada(yaExiste);return alert("Esta tienda ya registró su apuesta. No puede modificarse.");}const elecciones=partidos.map((p,i)=>({partido:`${p.local} VS ${p.visita}`,hora:p.hora,local:p.local,visita:p.visita,eleccion:document.getElementById(`pronostico_${i}`)?.value}));if(elecciones.some(e=>!e.eleccion))return alert("Completa todos los pronósticos.");const registro={id:`${jornada.numero}_${tienda}_${Date.now()}`,jornada:jornada.numero,fechaJornada:jornada.fecha,tienda,elecciones,fechaRegistro:new Date().toLocaleDateString("es-CL"),horaRegistro:new Date().toLocaleTimeString("es-CL",{hour:"2-digit",minute:"2-digit"})};try{const res=await apiPost("saveBet",{registro});if(!res.ok)throw new Error(res.error||"No guardó");await cargarDesdeServidor(false);ultimaApuesta=apuestas.find(a=>a.id===registro.id)||registro;}catch(e){apuestas.push(registro);localStorage.setItem("apuestas_wom",JSON.stringify(apuestas));ultimaApuesta=registro;alert("Guardado local. Para registro general conecta Google Sheets.");}mostrarApuestaGuardada(ultimaApuesta);cargarPronosticos();alert("Apuesta registrada correctamente.");}
function mostrarApuestaGuardada(registro){const btn=document.getElementById("btnGuardar"),box=document.getElementById("apuestaGuardada"),fecha=document.getElementById("fechaRegistro"),tienda=document.getElementById("tienda");if(btn)btn.style.display="none";if(box)box.classList.remove("hidden");if(fecha)fecha.textContent=`Registrada: ${registro.fechaRegistro} · ${registro.horaRegistro}`;if(tienda)tienda.disabled=true;partidos.forEach((_,i)=>{const select=document.getElementById(`pronostico_${i}`);if(select)select.disabled=true;});}
function resetFormularioApuesta(){const btn=document.getElementById("btnGuardar"),box=document.getElementById("apuestaGuardada"),tienda=document.getElementById("tienda");if(btn)btn.style.display="block";if(box)box.classList.add("hidden");if(tienda)tienda.disabled=false;partidos.forEach((_,i)=>{const select=document.getElementById(`pronostico_${i}`);if(select){select.disabled=false;select.value="";}});}
function cargarPronosticos(){const lista=document.getElementById("listaPronosticos");if(!lista)return;const data=apuestas.filter(a=>Number(a.jornada)===Number(jornada.numero));if(!data.length){lista.innerHTML=`<div class="info-card"><p>Aún no hay apuestas registradas.</p></div>`;return;}lista.innerHTML=data.map(a=>`<div class="prediction-card"><h3>🏪 ${escapeHTML(a.tienda)}</h3><small>Registrada: ${escapeHTML(a.fechaRegistro)} · ${escapeHTML(a.horaRegistro)}</small>${a.elecciones.map(e=>`<p><strong>⚽ ${escapeHTML(e.partido)}</strong><br><span>➡️ Elegimos: ${escapeHTML(e.eleccion)}</span></p>`).join("")}</div>`).join("");}
function cargarMetas(){setText("condicionDia",jornada.condicion);const cont=document.getElementById("metasTienda");if(!cont)return;cont.innerHTML=metas.map(t=>{const cumple=t.kpis.every(k=>Number(k.avance)>=Number(k.meta));const compite=Boolean(t.condicion)&&cumple;return `<div class="goal-row"><div class="goal-head"><strong>${escapeHTML(t.tienda)}</strong><span class="goal-status">${compite?"✅ En competencia":"❌ Pendiente"}</span></div><div class="condition-line">${t.condicion?"✅ Condición comercial cumplida":"❌ Condición comercial pendiente"}</div>${t.kpis.map(k=>{const pct=Math.min(Math.round((Number(k.avance)/Number(k.meta))*100),100);return `<div class="kpi-line"><small>${escapeHTML(k.nombre)}</small><div class="kpi-bar"><span style="width:${pct}%"></span></div><b>${formatKpi(k.avance,k.tipo)}/${formatKpi(k.meta,k.tipo)}</b></div>`;}).join("")}</div>`;}).join("");}
function cargarResultados(){const cont=document.getElementById("resultadosPartidos");if(cont){cont.innerHTML=partidos.map(p=>`<div class="result-card"><strong>⚽ ${escapeHTML(p.local)} VS ${escapeHTML(p.visita)}</strong><p>${escapeHTML(p.resultado||"Pendiente")}</p><small>${p.ganador?`Ganador: ${escapeHTML(p.ganador)}`:"Pendiente"}</small></div>`).join("");}const final=document.getElementById("resultadoJornada");if(!final)return;if(resultadoJornada.estado==="ganador"){final.innerHTML=`<div class="success-card"><h2>🏆 Ganador de la jornada</h2><p>${escapeHTML(resultadoJornada.ganador)}</p><p>${escapeHTML(resultadoJornada.aciertos)} aciertos</p><p>🎁 ${escapeHTML(jornada.premio)}</p></div>`;}else if(resultadoJornada.estado==="sin_ganador"){final.innerHTML=`<div class="info-card"><h2>⚠️ Sin ganador</h2><p>Ninguna tienda cumplió los requisitos para obtener el premio.</p></div>`;}else{final.innerHTML=`<p>${escapeHTML(resultadoJornada.mensaje||"Pendiente")}</p>`;}}
function compartirApuesta(){if(!ultimaApuesta)return alert("Primero guarda una apuesta.");const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext("2d");const grad=ctx.createLinearGradient(0,0,1080,1350);grad.addColorStop(0,"#23004d");grad.addColorStop(.45,"#090011");grad.addColorStop(1,"#6f00ff");ctx.fillStyle=grad;ctx.fillRect(0,0,1080,1350);ctx.fillStyle="rgba(255,47,146,.22)";ctx.fillRect(0,0,1080,18);ctx.fillStyle="#fff";ctx.font="bold 58px Arial";ctx.fillText("🏆 MUNDIAL",70,100);ctx.fillStyle="#ff2f92";ctx.font="bold 60px Arial";ctx.fillText("MULTIPRODUCTO",70,170);ctx.fillStyle="#fff";ctx.font="bold 34px Arial";ctx.fillText("WOM MERIDIONAL",70,225);drawCanvasCard(ctx,70,275,940,145);ctx.fillStyle="#fff";ctx.font="bold 40px Arial";ctx.fillText(`🏪 ${ultimaApuesta.tienda.toUpperCase()}`,110,340);ctx.fillStyle="#ff2f92";ctx.font="bold 34px Arial";ctx.fillText("⚽ NUESTRA APUESTA",110,395);ctx.fillStyle="#c9c3da";ctx.font="28px Arial";ctx.fillText(`Jornada ${ultimaApuesta.jornada} de ${jornada.total}`,110,445);let y=520;ultimaApuesta.elecciones.forEach(e=>{drawCanvasCard(ctx,70,y,940,145);ctx.fillStyle="#fff";ctx.font="bold 30px Arial";ctx.fillText(`⚽ ${e.partido}`,110,y+50);ctx.fillStyle="#ff2f92";ctx.font="bold 34px Arial";ctx.fillText(`➡️ Elegimos: ${e.eleccion}`,110,y+105);y+=160;});drawCanvasCard(ctx,70,1165,940,90);ctx.fillStyle="#fff";ctx.font="bold 28px Arial";ctx.fillText(`🎁 Premio: ${String(jornada.premio).replace("🍕 ","")}`,110,1218);ctx.fillStyle="#c9c3da";ctx.font="26px Arial";ctx.fillText(`Registrada: ${ultimaApuesta.fechaRegistro} · ${ultimaApuesta.horaRegistro}`,70,1290);ctx.fillStyle="#fff";ctx.font="bold 28px Arial";ctx.fillText("⚽ Pronostica • Cumple • Compite • Gana",70,1330);compartirCanvas(canvas,"apuesta-wom.png");}
function drawCanvasCard(ctx,x,y,w,h){ctx.fillStyle="rgba(22,14,40,.92)";ctx.strokeStyle="rgba(151,82,255,.46)";ctx.lineWidth=3;roundRect(ctx,x,y,w,h,26,true,true);}
function roundRect(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();if(fill)ctx.fill();if(stroke)ctx.stroke();}
function compartirCanvas(canvas,nombre){canvas.toBlob(async blob=>{const file=new File([blob],nombre,{type:"image/png"});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:"Mundial Multiproducto WOM",files:[file]});}else{const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=nombre;a.click();alert("Imagen generada. Se descargó para compartir por WhatsApp.");}});}
function validarAdmin(){const pass=document.getElementById("adminPass")?.value;if(pass!==ADMIN_PASS)return alert("Código incorrecto.");document.getElementById("adminLogin")?.classList.add("hidden");document.getElementById("adminContent")?.classList.remove("hidden");}
function cargarAdmin(){const input=document.getElementById("apiUrl");if(input)input.value=getApiUrl();}
function guardarApi(){const input=document.getElementById("apiUrl");if(!input)return;apiUrl=input.value.trim();localStorage.setItem("api_wom",apiUrl);alert("Conexión guardada.");}
function limpiarApuestasLocales(){localStorage.removeItem("apuestas_wom");apuestas=[];ultimaApuesta=null;cargarPronosticos();cargarFormularioApuesta();alert("Caché local limpiado.");}
function reabrirApuestaAdmin(){const tienda=prompt("Nombre exacto de la tienda a reabrir solo en este dispositivo:");if(!tienda)return;apuestas=apuestas.filter(a=>!(a.tienda===tienda&&Number(a.jornada)===Number(jornada.numero)));localStorage.setItem("apuestas_wom",JSON.stringify(apuestas));cargarPronosticos();cargarFormularioApuesta();alert(`Apuesta local reabierta para: ${tienda}`);}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value;}
function formatKpi(v,tipo){const n=Number(v);if(tipo==="$")return "$"+n.toLocaleString("es-CL");return String(v);}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function escapeAttr(v){return escapeHTML(v);}
